# Generated by Django 3.2 on 2022-12-09 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Articulo')),
                ('descripcion', models.TextField(blank=True, max_length=250, null=True, verbose_name='Descripcion')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('colorPrincipal', models.CharField(choices=[('', '-Seleccionar Color-'), (1, 'Amarillo'), (2, 'Azul'), (3, 'Celeste'), (4, 'Bordo'), (5, 'Rosa'), (6, 'Rojo'), (7, 'Marron'), (8, 'Verde'), (9, 'Violeta'), (10, 'Naranja'), (11, 'Blanco'), (12, 'Negro'), (13, 'Morado'), (14, 'Beige'), (15, 'Dorado'), (16, 'Plateado'), (17, 'Gris')], default='', max_length=2)),
                ('talla', models.CharField(choices=[('', '-Seleccionar Talla-'), (1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'XXL'), (6, 'XXXL'), (7, '30'), (8, '31'), (9, '32'), (10, '33'), (11, '34'), (12, '35'), (13, '36'), (14, '37'), (15, '38'), (16, '39'), (17, '40'), (18, '41'), (19, '42'), (20, '43'), (21, '44'), (22, '45'), (23, '46'), (24, '47'), (25, '48'), (26, '49'), (27, '50')], default='', max_length=2)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marca')),
            ],
        ),
    ]
